---
- name: Configure Jenkins nodes
  hosts: all
  roles:
    - jenkins/common
  tags:
    - jenkins

- name: Setup openshift
  hosts: openshift
  roles:
    - openshift
  tags:
    - openshift

- name: Setup jenkins slaves
  hosts: jenkins_slaves
  roles:
    - jenkins/slave
    - registry
    - nginx
  tags:
    - jenkins
    - jenkins/slaves

- name: Setup jenkins master
  hosts: jenkins_master
  roles:
    - jenkins/master
  tags:
    - jenkins
    - jenkins/master
