---
- name: Configure Jenkins nodes
  hosts: all
  roles:
    - jenkins/common
  tags:
    - jenkins

- name: Setup jenkins slaves
  hosts: jenkins_slaves
  roles:
    - jenkins/slave
    - registry
    - nginx
  tags:
    - jenkins
    - jenkins/slaves

- name: Setup jenkins master
  hosts: jenkins_master
  roles:
    - jenkins
    - jenkins/master

- name: Setup openshift
  hosts: openshift
  roles:
    - openshift
  tags:
    - openshift

- name: Fetch oc files
  hosts: openshift
  tasks:
    - name: Pull oc files from openshift
      synchronize:
        mode: pull
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - {src: /usr/bin/oc, dest: /tmp/oc}
        - {src: /var/lib/origin/openshift.local.config/master/ca.crt, dest: /tmp/oc_ca.crt}
      # delegate_to: localhost
  tags:
    - openshift/jenkins

- name: Push oc files to Jenkins slaves
  hosts: jenkins_slaves
  tasks:
    - name: Ensure /opt/cccp-service/client dir exists on Jenkins slaves
      file: dest=/opt/cccp-service/client state=directory

    - name: Push oc files to Jenkins slaves
      synchronize:
        mode: push
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - {src: /tmp/oc, dest: /usr/bin/oc}
        - {src: /tmp/oc_ca.crt, dest: /opt/cccp-service/client/ca.crt}

    - name: Get openshift build scripts and template json
      get_url:
        url: "{{ item }}"
        dest: /opt/cccp-service/client
      with_items:
        - https://raw.githubusercontent.com/bamachrn/cccp-service/master/client/build-project.sh
        - https://raw.githubusercontent.com/bamachrn/cccp-service/master/client/template.json
  tags:
    - openshift/jenkins
