---
- name: Enable Docker registry
  replace: >
    dest=/etc/sysconfig/docker
    regexp="^#\s*INSECURE_REGISTRY=.*"
    replace='INSECURE_REGISTRY="--insecure-registry 172.30.0.0/16"'

- name: Create openshift shared dirs
  file: name={{item}} state=directory
  with_items: "{{ openshift_shared_dirs }}"

- name: Set SELinux context for openshift shared dirs
  command: chcon -Rt svirt_sandbox_file_t {{ item }}
  with_items: "{{ openshift_shared_dirs }}"

- name: Run openshift docker image
  docker:
    name: origin
    image: "{{ origin_image_name }}"
    privileged: yes
    pid: host
    net: host
    volumes: "{{ openshift_volumes }}"
    command: start --master=https://"{{ansible_default_ipv4.address}}":8443 --etcd-dir="{{openshift_etcd_dir}}" --cors-allowed-origins=.*

- name: Wait for Openshift to come up
  pause: seconds=15

- name: Copy Openshift binaries
  command: docker cp origin:/usr/bin/openshift {{item}}
  with_items:
    - /usr/bin/oc
    - /usr/bin/oadm

- name: Ensure openshift binaries are executable
  file: dest="{{ item }}" mode="a+x"
  with_items:
    - /usr/bin/oc
    - /usr/bin/oadm

- name: Set perms for kubeconfig
  file: dest={{kubeconfig}} mode="go+r"
